### ISSUE TITLE
Where to find "utils".

### ISSUE THREAD

**Issue by guyuchao** [TonyLianLong/igligen#4]
In line:48: from utils.parser import load_args, but where to find "utils".

**Comment by TonyLianLong** [comment]
Is this causing import error on your end? Did it require changes to the code? If so, feel free to create a PR.

**Comment by zjysteven** [comment]
Hi @TonyLianLong I'm seeing the same issue here. Basically there seems to be a `utils` missing in the root directory.
https://github.com/TonyLianLong/igligen/blob/43f5072a7d0fbd7d8c00a123c982949ea63797aa/train_text_to_image_gligen_sam.py#L48

**Comment by TonyLianLong** [comment]
Just added the parser. Could you see if this solves the issue?

Sorry about that. It was omitted in the code refactoring process.

**Comment by zjysteven** [comment]
No worries. It works. Thanks!
