### ISSUE TITLE
Slow converenge in training.

### ISSUE THREAD

**Issue by guyuchao** [TonyLianLong/igligen#5]
I follow the guide to run the training (512, sdv2-base, 4gpu, bs32), but it seems converge very slowly and the loss/validation result are as follows. Is the training in the right track, and is the loss figure similar to yours.

<img width="846" alt="Screenshot 2024-05-23 at 7 51 53 AM" src="https://github.com/TonyLianLong/igligen/assets/31696690/ece75562-4b4c-41db-8026-dfcf896987f2">

**Comment by TonyLianLong** [comment]
Seems like you found out. It has sudden convergence like ControlNet. You need to train for a number of epochs.

**Comment by zjysteven** [comment]
> Seems like you found out. It has sudden convergence like ControlNet. You need to train for a number of epochs.

@TonyLianLong Thanks for making this repo and providing such valuable observation/experience. In your training run do you remember at how many steps the model started to follow the bounding box?

**Comment by TonyLianLong** [comment]
135.5k:
![image](https://github.com/TonyLianLong/igligen/assets/1451234/f4ffc495-b56c-4456-8d3b-9b2a9d2776d7)

140k: 
![image](https://github.com/TonyLianLong/igligen/assets/1451234/6f3fcaed-3801-439d-b204-8ec7f8f140ce)

145.5k: 
![image](https://github.com/TonyLianLong/igligen/assets/1451234/5cb76d3c-c797-4673-a546-d712fb35bcd2)

**Comment by TonyLianLong** [comment]
My loss looks like this (no significant difference before vs after convergence)

<img width="542" alt="image" src="https://github.com/TonyLianLong/igligen/assets/1451234/292602d9-630e-49bc-9800-7caa886df2dc">
